### ISSUE TITLE
creates invalid state-change-handler

### ISSUE THREAD

**Issue by TanninOne** [agc93/wingvortex#1]
https://github.com/agc93/wingvortex/blob/2c7bdd661ab1e26d53dd0b4d398e51483285db78/src/index.ts#L135-L138

This function is supposed to return a function but this early out returns undefined.

**Comment by agc93** [comment]
oh of course! I actually spotted that in the logs but couldn't really tell where it was coming from. Thanks for spotting the culprit, I'll get that fixed soon.

**Comment by agc93** [comment]
This should be resolve in the latest update.
